### ISSUE TITLE
Is there a way to hide new info from url of the app?

### ISSUE THREAD

**Issue by JohnnyVizz** [uiucanh/streamlit-google-oauth#4]
I noticed that once the script is ran you have a lot of info after the apps url.

in example: http://localhost:8504/?code=4%2F*AX4Xf*haR9***b*M**-_Yiv*K*vm9-*d*Ey*W*&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=2&prompt=consent#

Is there any way to clear this up? 
It's crucial since I'm planning to use your auth code in my public web app.

**Comment by michaelhball** [comment]
You can use `st.experimental_set_query_params()` with no arguments to clear the query params, so call this somewhere after getting the `code`.

**Comment by JohnnyVizz** [comment]
> You can use `st.experimental_set_query_params()` with no arguments to clear the query params, so call this somewhere after getting the `code`.

Massive thanks! It worked like a charm

**Comment by JohnnyVizz** [comment]
> You can use `st.experimental_set_query_params()` with no arguments to clear the query params, so call this somewhere after getting the `code`.

Just had a thought, I suppose you can use it the other way too? If I want to add direct link to some part of the app, right?
